### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [extremecoders-re/PjOrion-Deobfuscator#1]
My cmd window..

```
C:\Windows\system32>python C:\****\PjOrion-Deobfuscator\generateCFG.py C:\***\mod.pyc

Traceback (most recent call last):
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 436, in <module>
    main()
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 431, in main
    recurseCodeObjects(code_obj)
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 413, in recurseCodeObjects
    drawCFG(c_obj, '{}{}.svg'.format(filenameprefix, i))
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 392, in drawCFG
    leader_set = getLeaders(code_obj, oep)
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 256, in getLeaders
    instr = disassembler.disas(offset)
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 130, in disas
    assert offset < len(self.c_stream)
AssertionError
```

**Comment by Stabmeqt** [comment]
same problem with other file. I wonder if author plan to continue development?
