### ISSUE TITLE
Error on example file

### ISSUE THREAD

**Issue by ghost** [extremecoders-re/PjOrion-Deobfuscator#2]
I have installed all packages and run it on the example file ?

```
C:\Windows\system32>pip install pyparsing
Requirement already satisfied (use --upgrade to upgrade): pyparsing in c:\program files (x86)\python27\lib\site-packages

C:\Windows\system32>pip install graphviz
Requirement already satisfied (use --upgrade to upgrade): graphviz in c:\program files (x86)\python27\lib\site-packages

C:\Windows\system32>pip install pydotplus
Requirement already satisfied (use --upgrade to upgrade): pydotplus in c:\program files (x86)\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=2.0.1 in c:\program files (x86)\python27\lib\site-packages (from pydotplus)

C:\Windows\system32>python C:\****\PjOrion-Deobfuscator\generateCFG.py C:\Users\Philipp\Desktop\PjOrion-Deobfuscator\example\example1.pyc
Traceback (most recent call last):
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 436, in <module>
    main()
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 431, in main
    recurseCodeObjects(code_obj)
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 413, in recurseCodeObjects
    drawCFG(c_obj, '{}{}.svg'.format(filenameprefix, i))
  File "C:\****\PjOrion-Deobfuscator\generateCFG.py", line 404, in drawCFG
    graph.write_svg(filename)
  File C:\****\PjOrion-Deobfuscator\generateCFG.py", line 1810, in <lambda>
    prog=self.prog: self.write(path, format=f, prog=prog)
  File "C:\****\Python27\lib\site-packages\pydotplus\graphviz.py", line 1918, in write
    fobj.write(self.create(prog, format))
  File "C:\****\Python27\lib\site-packages\pydotplus\graphviz.py", line 1960, in create
    'GraphViz\'s executables not found')
pydotplus.graphviz.InvocationException: GraphViz's executables not found
```

**Comment by extremecoders-re** [comment]
@alkoforumm Looks like  graphviz executables are not present on the system path. What is the output of the path command.
