### ISSUE TITLE
bad marshal data

### ISSUE THREAD

**Issue by w3lld0ne** [extremecoders-re/PjOrion-Deobfuscator#3]
D:\PjOrion-Deobfuscator-master>generatecfg.py example\example1.pyc
Traceback (most recent call last):
  File "D:\PjOrion-Deobfuscator-master\generateCFG.py", line 436, in <module>
    main()
  File "D:\PjOrion-Deobfuscator-master\generateCFG.py", line 430, in main
    code_obj = marshal.load(fSrc)
ValueError: bad marshal data (unknown type code)

**Comment by stealthz67** [comment]
it's just ridiculous, not even close)))

пн, 23 мар. 2020 г., 18:38 Alex <notifications@github.com>:
